export const FETCHING_MESSAGES = 'FETCH_MESSAGES';
export const FETCHING_MESSAGES_SUCCESS = 'FETCHING_MESSAGES_SUCCESS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const INCOMING_MESSAGE = 'INCOMING_MESSAGE';
export const FINISH_FETCHING = 'FINISH_FETCHING';
